// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI6Qg7vksajDwRj5fSJseE20havSFZDbI',
    appId: '1:1032297134307:web:d1396aff4299ca90d56dd6',
    messagingSenderId: '1032297134307',
    projectId: 'curely-f7f4e',
    authDomain: 'curely-f7f4e.firebaseapp.com',
    storageBucket: 'curely-f7f4e.firebasestorage.app',
    measurementId: 'G-HBCECNWZDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArexVtC2uu5spppH8eGZqXY_GirAQ5Ic8',
    appId: '1:1032297134307:android:bd10a5ae0d62681ed56dd6',
    messagingSenderId: '1032297134307',
    projectId: 'curely-f7f4e',
    storageBucket: 'curely-f7f4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWGZ60Nd2zsXQ3p-pchbNc9qxxYIKOC-0',
    appId: '1:1032297134307:ios:06b67c5b7574134ad56dd6',
    messagingSenderId: '1032297134307',
    projectId: 'curely-f7f4e',
    storageBucket: 'curely-f7f4e.firebasestorage.app',
    iosBundleId: 'com.example.curely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWGZ60Nd2zsXQ3p-pchbNc9qxxYIKOC-0',
    appId: '1:1032297134307:ios:06b67c5b7574134ad56dd6',
    messagingSenderId: '1032297134307',
    projectId: 'curely-f7f4e',
    storageBucket: 'curely-f7f4e.firebasestorage.app',
    iosBundleId: 'com.example.curely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI6Qg7vksajDwRj5fSJseE20havSFZDbI',
    appId: '1:1032297134307:web:5cadcaae131a7d18d56dd6',
    messagingSenderId: '1032297134307',
    projectId: 'curely-f7f4e',
    authDomain: 'curely-f7f4e.firebaseapp.com',
    storageBucket: 'curely-f7f4e.firebasestorage.app',
    measurementId: 'G-NJ5TYF0DH8',
  );
}
